import type { SceneTemplate } from "../types";

export const FOOD_PROCESS_SCENES: SceneTemplate[] = [
  {
    key: "source",
    purpose: "Source ingredients introduction",
    priority: 1,
    narration: "Every great product begins with quality ingredients at the source.",
    visualDescription: "Establishing shot of fresh raw ingredients in natural setting or farm, workers harvesting, baskets and crates of primary ingredients",
    cameraMovement: "slow aerial drift",
    cameraAngle: "wide establishing shot",
    lighting: "warm natural golden hour or bright farm daylight",
    environment: "farm, plantation, or artisan ingredient source",
    soundEffects: ["birds", "rustling leaves"],
    musicMood: "organic warmth",
    caption: "RAW INGREDIENTS",
    emotion: "wholesome",
    transition: "cut",
  },
  {
    key: "transport",
    purpose: "Transport to facility",
    priority: 3,
    narration: "Ingredients travel to the production facility where transformation begins.",
    visualDescription: "Delivery truck arriving at food production facility, workers unloading crates of ingredients into clean loading bay",
    cameraMovement: "tracking shot alongside truck",
    cameraAngle: "medium wide shot",
    lighting: "morning industrial daylight",
    environment: "food factory loading dock",
    soundEffects: ["truck engine", "crate movement"],
    musicMood: "journey",
    caption: "TRANSPORT",
    emotion: "anticipation",
    transition: "cut",
  },
  {
    key: "prep",
    purpose: "Ingredient preparation",
    priority: 1,
    narration: "Ingredients are sorted, cleaned, and prepared with care.",
    visualDescription: "Workers in white coats sorting and washing ingredients on stainless steel tables, close-ups of hands handling natural textures, steam and water mist",
    cameraMovement: "slow tracking along prep tables",
    cameraAngle: "medium close-up",
    lighting: "bright clean kitchen-industrial lighting",
    environment: "food preparation room, stainless surfaces",
    soundEffects: ["water rinse", "knife chopping"],
    musicMood: "methodical",
    caption: "PREPARATION",
    emotion: "careful",
    transition: "cut",
  },
  {
    key: "processing",
    purpose: "Core processing stage",
    priority: 1,
    narration: "Heat, time, and precision transform raw ingredients into something extraordinary.",
    visualDescription: "Industrial food processing machines in action — mixing, roasting, grinding, or cooking — realistic steam, natural food colors, workers monitoring gauges",
    cameraMovement: "dynamic side tracking",
    cameraAngle: "medium factory shot",
    lighting: "warm processing glow mixed with overhead industrial lights",
    environment: "food production floor with active machinery",
    soundEffects: ["mixer hum", "steam release"],
    musicMood: "transformation",
    caption: "PROCESSING",
    emotion: "intense",
    transition: "cut",
  },
  {
    key: "refining",
    purpose: "Refining and quality",
    priority: 2,
    narration: "The product is refined until texture, color, and flavor meet exact standards.",
    visualDescription: "Close-ups of product flowing through pipes or conveyors, quality inspector sampling, smooth refined texture macro shots",
    cameraMovement: "macro push-in",
    cameraAngle: "close-up macro",
    lighting: "warm appetizing product lighting",
    environment: "refining and quality control area",
    soundEffects: ["flowing product", "inspection clicks"],
    musicMood: "refined",
    caption: "REFINING",
    emotion: "satisfying",
    transition: "cut",
  },
  {
    key: "molding",
    purpose: "Forming final shape",
    priority: 2,
    narration: "The product takes its familiar final shape.",
    visualDescription: "Molding, cutting, or forming machines shaping the product, conveyor carrying uniform pieces, robotic or manual placement into forms",
    cameraMovement: "overhead conveyor tracking",
    cameraAngle: "overhead production shot",
    lighting: "clean commercial food lighting",
    environment: "forming and molding station",
    soundEffects: ["machine press", "conveyor belt"],
    musicMood: "rhythmic",
    caption: "FORMING",
    emotion: "rhythmic",
    transition: "cut",
  },
  {
    key: "cooling",
    purpose: "Cooling or resting",
    priority: 3,
    narration: "A crucial resting stage ensures perfect consistency.",
    visualDescription: "Product cooling on conveyor or racks, condensation and steam fading, time-lapse feel of settling texture",
    cameraMovement: "slow pan across cooling racks",
    cameraAngle: "wide medium shot",
    lighting: "cool soft industrial lighting",
    environment: "cooling tunnel or resting room",
    soundEffects: ["gentle fan hum"],
    musicMood: "calm",
    caption: "COOLING",
    emotion: "patient",
    transition: "cut",
  },
  {
    key: "packaging",
    purpose: "Packaging",
    priority: 1,
    narration: "Finished products are sealed, labeled, and prepared for delivery.",
    visualDescription: "Automated packaging line wrapping products, labels applied, boxes filled and sealed, workers stacking cartons",
    cameraMovement: "tracking along packaging line",
    cameraAngle: "medium line shot",
    lighting: "bright commercial packaging lighting",
    environment: "packaging and labeling department",
    soundEffects: ["wrapper machine", "label printer"],
    musicMood: "efficient",
    caption: "PACKAGING",
    emotion: "complete",
    transition: "cut",
  },
  {
    key: "hero",
    purpose: "Finished product hero",
    priority: 1,
    narration: "From humble ingredients to the finished product — crafted with care.",
    visualDescription: "Cinematic hero shot of beautifully presented finished food product, production line softly blurred in background, slow camera movement, appetizing commercial lighting",
    cameraMovement: "slow cinematic orbit",
    cameraAngle: "low-angle hero product shot",
    lighting: "premium appetizing commercial lighting",
    environment: "product showcase with factory backdrop",
    soundEffects: ["soft ambience"],
    musicMood: "triumphant",
    caption: "FINISHED PRODUCT",
    emotion: "delight",
    transition: "fade",
  },
];
