import type { SceneTemplate } from "../types";

export const FOOD_PROCESS_SCENES: SceneTemplate[] = [
  {
    key: "source",
    purpose: "Active harvesting at source",
    priority: 1,
    narration:
      "Farm workers cut and gather fresh ingredients by hand, loading woven baskets that move toward the collection truck.",
    visualDescription:
      "Golden-hour farm: workers bend to harvest crops, hands cutting and placing produce into woven baskets on moving cart; tractor slowly pulls loaded crates along dirt path — continuous harvesting motion, not static pile of food",
    cameraMovement: "slow aerial drift following cart",
    cameraAngle: "wide establishing shot",
    lighting: "warm natural golden hour daylight",
    environment: "active farm or plantation with workers harvesting",
    soundEffects: ["birds", "rustling leaves", "basket movement"],
    musicMood: "organic",
    caption: "",
    emotion: "wholesome",
    transition: "cut",
  },
  {
    key: "transport",
    purpose: "Unloading at facility",
    priority: 3,
    narration:
      "A delivery truck backs into the loading bay while workers roll crate dollys of ingredients through the hygiene airlock into the prep room.",
    visualDescription:
      "Food factory dock: refrigerated truck doors open, workers in white coats wheel crate dollys off lift gate through stainless airlock doors into bright prep area — forklifts and dollies in motion",
    cameraMovement: "tracking alongside unloading",
    cameraAngle: "medium wide shot",
    lighting: "morning industrial daylight",
    environment: "food factory loading dock with active unloading",
    soundEffects: ["truck engine", "dolly wheels", "crate movement"],
    musicMood: "journey",
    caption: "",
    emotion: "anticipation",
    transition: "cut",
  },
  {
    key: "prep",
    purpose: "Washing and sorting in motion",
    priority: 1,
    narration:
      "On stainless prep tables, gloved hands rinse ingredients under spray nozzles, sort them into trays, and push trays onto the outgoing conveyor.",
    visualDescription:
      "Prep room: workers in hair nets wash ingredients under running spray, scrub and sort into stainless trays, slide trays onto moving conveyor belt; steam and water mist, knives chopping on rhythm — hands constantly working",
    cameraMovement: "tracking along prep tables",
    cameraAngle: "medium close-up hands and conveyor",
    lighting: "bright clean kitchen-industrial lighting",
    environment: "food preparation room with running conveyors",
    soundEffects: ["water spray", "knife chopping", "conveyor"],
    musicMood: "methodical",
    caption: "",
    emotion: "careful",
    transition: "cut",
  },
  {
    key: "processing",
    purpose: "Machines actively processing",
    priority: 1,
    narration:
      "Ingredients pour into industrial mixers and roasters, steam vents pulse, and a worker adjusts a valve as product flows through heated pipes.",
    visualDescription:
      "Production floor: ingredients dump from hopper into spinning mixer, steam bursts from roast drum, viscous product pumps through stainless pipes into next vessel; worker turns valve wheel and monitors gauge — all machines running",
    cameraMovement: "dynamic side tracking",
    cameraAngle: "medium factory shot",
    lighting: "warm processing glow with overhead industrial lights",
    environment: "active food processing floor",
    soundEffects: ["mixer hum", "steam release", "pipe flow"],
    musicMood: "transformation",
    caption: "",
    emotion: "intense",
    transition: "cut",
  },
  {
    key: "refining",
    purpose: "Product flowing and inspected",
    priority: 2,
    narration:
      "Smooth product streams through a refining nozzle while an inspector scoops a sample, rubs it between gloved fingers, and nods before the line continues.",
    visualDescription:
      "Refining line: glossy product flows through polished pipe into wide tray, inspector scoops sample with stainless ladle, examines texture, releases sample back as conveyor carries uniform stream onward — liquid or paste in continuous motion",
    cameraMovement: "macro push-in along flowing product",
    cameraAngle: "close-up macro",
    lighting: "warm appetizing product lighting",
    environment: "refining and QC station with active flow",
    soundEffects: ["flowing product", "ladle scoop"],
    musicMood: "refined",
    caption: "",
    emotion: "satisfying",
    transition: "cut",
  },
  {
    key: "molding",
    purpose: "Forming machines shaping product",
    priority: 2,
    narration:
      "A forming press stamps uniform pieces onto a moving belt while robotic or manual arms place them into trays that advance to the cooler.",
    visualDescription:
      "Forming station: mechanical press stamps product shapes onto green conveyor, worker transfers pieces into trays, trays advance into cooling tunnel entrance — press cycles repeatedly",
    cameraMovement: "overhead conveyor tracking",
    cameraAngle: "overhead production shot",
    lighting: "clean commercial food lighting",
    environment: "forming station with cycling press",
    soundEffects: ["press cycle", "conveyor belt"],
    musicMood: "rhythmic",
    caption: "",
    emotion: "rhythmic",
    transition: "cut",
  },
  {
    key: "cooling",
    purpose: "Cooling tunnel in motion",
    priority: 3,
    narration:
      "Trays ride through a cooling tunnel as fans spin and condensation fades from the product surface.",
    visualDescription:
      "Cooling tunnel: trays on conveyor enter chilled tunnel, fan blades rotate, product surfaces show fading steam; trays exit to worker who lifts corner of tray and slides it to packaging queue — continuous belt motion",
    cameraMovement: "slow pan following trays through tunnel",
    cameraAngle: "wide medium shot",
    lighting: "cool soft industrial lighting",
    environment: "cooling tunnel with moving conveyor",
    soundEffects: ["fan hum", "conveyor"],
    musicMood: "calm",
    caption: "",
    emotion: "patient",
    transition: "cut",
  },
  {
    key: "packaging",
    purpose: "Wrapping and sealing line",
    priority: 1,
    narration:
      "Finished pieces enter a wrapper, seals form along the edges, and cartons are filled and pushed down the line by mechanical pusher arms.",
    visualDescription:
      "Packaging line: product enters flow wrapper, film seals around pieces, cutter slices continuous stream; cartons filled by descending chute, mechanical pusher slides carton forward, worker stacks sealed carton on pallet — line running",
    cameraMovement: "tracking along packaging line",
    cameraAngle: "medium line shot",
    lighting: "bright commercial packaging lighting",
    environment: "packaging department with active machines",
    soundEffects: ["wrapper machine", "carton slide"],
    musicMood: "efficient",
    caption: "",
    emotion: "complete",
    transition: "cut",
  },
  {
    key: "hero",
    purpose: "Finished product on moving line",
    priority: 1,
    narration:
      "Perfectly formed products advance on the outbound conveyor while the production floor hums behind them.",
    visualDescription:
      "Low-angle tracking shot along outbound conveyor carrying rows of finished food products, workers and machines soft-focused in background still operating, slow cinematic camera move — products moving toward camera, not static plate shot",
    cameraMovement: "slow cinematic tracking along conveyor",
    cameraAngle: "low-angle tracking shot",
    lighting: "premium appetizing commercial lighting",
    environment: "active production floor with outbound conveyor",
    soundEffects: ["conveyor", "soft ambience"],
    musicMood: "triumphant",
    caption: "",
    emotion: "delight",
    transition: "fade",
  },
];
