import type { SceneTemplate } from "../types";

/**
 * Smartphone manufacturing — every scene shows real factory action, zero on-screen text.
 */
export const MANUFACTURING_SCENES: SceneTemplate[] = [
  {
    key: "factory_intro",
    purpose: "Establish active factory exterior and entry",
    priority: 1,
    narration:
      "Delivery trucks roll into the loading bay while workers in helmets and safety glasses walk through the doors into a running production facility.",
    visualDescription:
      "Wide aerial drone shot pushing toward a vast smartphone factory at dawn; refrigerated trucks backing into loading docks, forklift moving pallet crates of components, workers in navy uniforms and white helmets briskly entering through glass doors while conveyor hum is visible through windows — active facility, not empty",
    cameraMovement: "slow cinematic drone push-in",
    cameraAngle: "wide aerial establishing shot",
    lighting: "soft morning light, cool white LED glow from factory interior",
    environment: "operating manufacturing campus, active loading bays, moving vehicles",
    soundEffects: ["truck engines", "forklift", "industrial ambience"],
    musicMood: "documentary",
    caption: "",
    emotion: "awe",
    transition: "cut",
  },
  {
    key: "raw_materials",
    purpose: "Workers inspect incoming components in motion",
    priority: 1,
    narration:
      "A technician slides antistatic trays along an inspection conveyor, lifting tempered glass and aluminum frame pieces under magnifier lamps before releasing them to the next station.",
    visualDescription:
      "Incoming QC station: worker's gloved hands pick up brushed aluminum phone frame from moving conveyor, rotate it under bright inspection lamp, place glass panel onto comparison fixture; trays of green PCBs, camera lens modules, battery cells, and OLED panels pass on parallel belt — hands contact every object, belts continuously moving",
    cameraMovement: "tracking along moving conveyor at tray height",
    cameraAngle: "medium close-up worker hands and components",
    lighting: "bright inspection LEDs, shallow depth of field on metal and glass",
    environment: "incoming materials QC line with active conveyors and inspection lamps",
    soundEffects: ["conveyor belt", "component tray slide"],
    musicMood: "focused",
    caption: "",
    emotion: "meticulous",
    transition: "cut",
  },
  {
    key: "component_mfg",
    purpose: "CNC and robots actively machining frames",
    priority: 2,
    narration:
      "An orange six-axis robotic arm lifts a raw aluminum slab, places it into a CNC fixture, and the spindle begins cutting the phone frame profile while coolant mist sprays.",
    visualDescription:
      "CNC cell in operation: robotic arm picks metal blank from rack, inserts into machining fixture, clamps engage, CNC spindle cuts phone frame contour with coolant spray; adjacent station robot transfers cut frame to rinse bath — continuous mechanical motion, metal shavings visible",
    cameraMovement: "side tracking following robotic arm path",
    cameraAngle: "medium factory shot",
    lighting: "crisp white industrial LED, metallic reflections on coolant",
    environment: "active CNC fabrication floor with running machines",
    soundEffects: ["CNC spindle", "robotic servos", "coolant mist"],
    musicMood: "industrial",
    caption: "",
    emotion: "precise",
    transition: "cut",
  },
  {
    key: "pcb_assembly",
    purpose: "SMT line placing components on moving PCB",
    priority: 1,
    narration:
      "Bare circuit boards ride the SMT conveyor into a pick-and-place machine where nozzles dart down and place microchips onto solder paste at high speed.",
    visualDescription:
      "Overhead view of SMT line: green PCB advances on conveyor into pick-and-place machine, multiple nozzles rapidly pick tiny components from feeders and place onto board positions; macro cut to solder paste dots, then board enters reflow oven tunnel glowing orange; engineer leans in adjusting feeder reel — all equipment running",
    cameraMovement: "overhead line tracking then macro push-in",
    cameraAngle: "overhead production line and macro",
    lighting: "bright technical lighting, green PCB contrast",
    environment: "electronics assembly hall, active SMT machines",
    soundEffects: ["pick-and-place rhythm", "conveyor", "reflow hum"],
    musicMood: "technological",
    caption: "",
    emotion: "rapid",
    transition: "cut",
  },
  {
    key: "display_mfg",
    purpose: "Robots handling and testing displays",
    priority: 2,
    narration:
      "Vacuum robotic grippers lift an OLED panel from a stack, align it under optical scanners, then a roller applies protective film as the display powers on for pixel test.",
    visualDescription:
      "Display clean zone: robotic vacuum gripper lifts glass OLED panel from antistatic stack, rotates for optical camera scan, defect map flashes on monitor edge (blurred unreadable UI); protective film roller presses across screen; display illuminates color test pattern while gripper transfers panel to outgoing conveyor",
    cameraMovement: "slow push-in following panel through stations",
    cameraAngle: "close-up manufacturing shot",
    lighting: "display backlight glow in dim inspection booth",
    environment: "display bonding and inspection clean zone",
    soundEffects: ["vacuum gripper", "film roller", "conveyor"],
    musicMood: "sleek",
    caption: "",
    emotion: "careful",
    transition: "cut",
  },
  {
    key: "battery_assembly",
    purpose: "Battery installed into phone chassis",
    priority: 2,
    narration:
      "A technician guides a lithium cell into a phone mid-frame using a precision alignment tool while a robotic station on the next fixture prepares the following chassis.",
    visualDescription:
      "Battery station: worker in safety glasses positions lithium battery cell into midnight blue phone chassis on fixture using alignment jig, presses until click-seat, torques retention bracket; parallel robotic arm on adjacent station picks next cell from inspection tray and moves toward waiting frame — hands and robot both in motion",
    cameraMovement: "robotic-arm POV then side angle on technician hands",
    cameraAngle: "medium side assembly shot",
    lighting: "clean neutral factory overhead LEDs",
    environment: "battery installation station with dual fixtures",
    soundEffects: ["alignment click", "robotic gripper", "torque driver"],
    musicMood: "cautious",
    caption: "",
    emotion: "careful",
    transition: "cut",
  },
  {
    key: "camera_assembly",
    purpose: "Camera module assembly and calibration",
    priority: 2,
    narration:
      "Micro robotic dispensers apply adhesive, place lens elements into camera housing, and a calibration rig projects alignment beams across the triple-camera module.",
    visualDescription:
      "Optical assembly bench: macro shot of lens dropping into camera barrel under robotic dispenser, sensor board seated by micro gripper; triple-camera module rotates on calibration rig with laser alignment beams sweeping; finished module placed into output tray by robotic arm — continuous micro-assembly motion",
    cameraMovement: "extreme macro orbit around module",
    cameraAngle: "extreme macro close-up",
    lighting: "dramatic macro with lens reflections",
    environment: "camera module assembly lab inside factory",
    soundEffects: ["precision clicks", "calibration tone"],
    musicMood: "intricate",
    caption: "",
    emotion: "intricate",
    transition: "cut",
  },
  {
    key: "phone_assembly_1",
    purpose: "Motherboard installed into frame",
    priority: 1,
    narration:
      "On the main line, a robotic arm lowers the motherboard into an empty midnight blue frame while an automated driver torques screws along the bracket rails.",
    visualDescription:
      "Main assembly line: empty aluminum phone frame clamped on moving pallet; robotic arm descends with green motherboard, aligns connectors, presses into frame; automated screw driver travels along rail torquing fasteners; frame advances on conveyor to next station — synchronized line motion",
    cameraMovement: "tracking along assembly line pallet",
    cameraAngle: "side-angle assembly shot",
    lighting: "bright assembly station lighting",
    environment: "main phone assembly conveyor line",
    soundEffects: ["screw torque", "conveyor pallet"],
    musicMood: "momentum",
    caption: "",
    emotion: "building",
    transition: "cut",
  },
  {
    key: "phone_assembly_2",
    purpose: "Display and back panel installed",
    priority: 1,
    narration:
      "The display panel is seated and pressed into the frame, triple cameras are torqued onto the back, and the back panel is aligned and sealed as the phone rotates on the fixture.",
    visualDescription:
      "Final assembly station: robotic press seats edge-to-edge OLED display into frame; worker mounts triple camera modules on back and tightens fasteners; back panel lowered by robotic arm, alignment pins engage, adhesive press closes; completed midnight blue smartphone rotates on fixture while conveyor carries next frame in — full assembly action",
    cameraMovement: "smooth orbit around rotating fixture",
    cameraAngle: "medium product assembly shot",
    lighting: "premium reflections on glass and aluminum",
    environment: "final assembly and seal station",
    soundEffects: ["panel press", "fastener torque", "seal press"],
    musicMood: "crescendo",
    caption: "",
    emotion: "satisfying",
    transition: "cut",
  },
  {
    key: "quality_control",
    purpose: "Active QC testing on moving line",
    priority: 1,
    narration:
      "Phones roll through automated test tunnels where robotic probes tap the touchscreen, cameras capture color charts, and speakers emit test tones while engineers watch live waveforms.",
    visualDescription:
      "QC tunnel: phone on conveyor enters automated touchscreen test where robotic finger traces patterns on live screen; camera faces color calibration chart and snaps test burst; speaker grille emits tone while waveform animates on side monitor; drop-test rig arm swings in background; engineer adjusts fixture knob — continuous testing motion",
    cameraMovement: "tracking through QC tunnel",
    cameraAngle: "medium wide QC line",
    lighting: "clinical bright testing lighting",
    environment: "quality control testing hall with active stations",
    soundEffects: ["test tones", "conveyor rollers", "probe taps"],
    musicMood: "assured",
    caption: "",
    emotion: "confident",
    transition: "cut",
  },
  {
    key: "final_cleaning",
    purpose: "Cleaning and film application in motion",
    priority: 3,
    narration:
      "Rotating brushes polish the glass surface while a film applicator rolls protective layer across the screen before a gripper lifts the phone into final visual inspection.",
    visualDescription:
      "Finishing station: phone held in rotating clamp, soft brushes polish glass; protective film applicator roller moves across screen; robotic gripper transfers phone under bright inspection cone; inspector nods and releases unit to outgoing belt — all stations active",
    cameraMovement: "slow push-in along finishing line",
    cameraAngle: "close-up finishing shot",
    lighting: "sparkling highlight on polished glass",
    environment: "cleaning and finishing conveyor station",
    soundEffects: ["polishing brush", "film roller"],
    musicMood: "polished",
    caption: "",
    emotion: "pristine",
    transition: "cut",
  },
  {
    key: "packaging",
    purpose: "Automated boxing line",
    priority: 1,
    narration:
      "Robotic arms place each phone into a minimalist white box, lay cable and inserts, close the lid, and a mechanical arm stacks finished cartons on the outbound pallet.",
    visualDescription:
      "Packaging line: robotic gripper places smartphone into plain white retail box without readable branding, drops USB-C cable and cardboard insert, lid closes on mechanical press; label printer arm moves but label faces away from camera; box conveyed to stacker robot placing carton on growing pallet — continuous packaging motion",
    cameraMovement: "overhead packaging line tracking",
    cameraAngle: "overhead and medium alternating",
    lighting: "clean commercial packaging lighting",
    environment: "automated outbound packaging line",
    soundEffects: ["box press", "conveyor", "stacker arm"],
    musicMood: "efficient",
    caption: "",
    emotion: "complete",
    transition: "cut",
  },
  {
    key: "hero_shot",
    purpose: "Active factory finale with moving line",
    priority: 1,
    narration:
      "Finished identical smartphones ride the outbound conveyor past assembly stations still running, a slow camera move revealing the scale of production.",
    visualDescription:
      "Low-angle cinematic dolly: row of identical midnight blue smartphones advancing on green conveyor belt, robotic arms working in soft-focus background, stacked plain white boxes on pallet, warm factory LEDs overhead — production line still operating, phones moving toward camera, no static table shot",
    cameraMovement: "slow cinematic dolly with parallax",
    cameraAngle: "low-angle tracking along conveyor",
    lighting: "premium commercial with realistic factory bokeh",
    environment: "active factory floor, outbound conveyor and running line",
    soundEffects: ["conveyor", "distant robotic servos"],
    musicMood: "triumphant",
    caption: "",
    emotion: "premium",
    transition: "fade",
  },
];
