import type { SceneTemplate } from "../types";

/**
 * NovaTech X9 hyper-realistic manufacturing documentary — cause-and-effect physical work per stage.
 * Simple motion per shot: 1-2 subjects, controlled camera (per hyperrealism best practices).
 */
export const MANUFACTURING_SCENES: SceneTemplate[] = [
  {
    key: "factory_intro",
    purpose: "Wide establishing — scale of fictional realistic plant",
    priority: 1,
    narration:
      "Trucks arrive at the loading bay as workers enter an operating smartphone production facility.",
    visualDescription:
      "Wide establishing shot: vast smartphone factory at dawn, trucks backing into docks, forklift moving pallets, workers in navy uniforms entering through doors — active plant with visible conveyor glow through windows, subtle floor wear and cable runs",
    cameraMovement: "slow controlled push-in, not excessive drone spin",
    cameraAngle: "wide establishing shot",
    lighting: "soft morning daylight mixing with cool factory LED spill",
    environment: "manufacturing campus, active loading docks",
    soundEffects: ["truck engines", "forklift", "distant conveyor hum"],
    musicMood: "subtle documentary",
    caption: "",
    emotion: "awe",
    transition: "cut",
  },
  {
    key: "component_receiving",
    purpose: "Raw components arrive and move on belt",
    priority: 1,
    narration:
      "Incoming trays of glass, aluminum blanks, and circuit boards slide along the receiving conveyor for inspection.",
    visualDescription:
      "Receiving line: antistatic trays with tempered glass panels and aluminum blanks advance on green conveyor; worker gloved hands lift one frame blank, rotates under magnifier lamp, sets it back on moving belt — parallel tray of green PCBs passes continuously",
    cameraMovement: "slow tracking at conveyor height",
    cameraAngle: "medium close-up hands and belt",
    lighting: "bright inspection LEDs, shallow depth of field",
    environment: "incoming component receiving station",
    soundEffects: ["conveyor belt", "tray slide"],
    musicMood: "focused",
    caption: "",
    emotion: "meticulous",
    transition: "cut",
  },
  {
    key: "frame_machining",
    purpose: "Worker places frame — CNC machines — inspect",
    priority: 1,
    narration:
      "A worker places an aluminum phone frame into a machining fixture, the machine clamps it, the cutting tool moves in, and metal particles spray as the frame is machined.",
    visualDescription:
      "Cause-effect machining: worker places raw aluminum phone frame into CNC fixture, clamps close audibly, cutting tool advances into frame profile, coolant mist and fine metal particles visible, spindle retracts, worker removes finished midnight-blue frame blank and inspects edge under lamp — no skipped steps",
    cameraMovement: "static camera with slight handheld documentary micro-movement",
    cameraAngle: "medium side shot on fixture",
    lighting: "crisp industrial LED with metallic coolant reflections",
    environment: "CNC machining cell with visible tool wear marks",
    soundEffects: ["clamp close", "CNC spindle", "coolant mist"],
    musicMood: "industrial",
    caption: "",
    emotion: "precise",
    transition: "cut",
  },
  {
    key: "glass_prep",
    purpose: "Glass panels cut and inspected",
    priority: 2,
    narration:
      "Glass sheets feed through a cutting station where a scoring wheel traces the display outline before panels are separated and inspected.",
    visualDescription:
      "Glass prep station: large glass sheet advances, automated scoring wheel traces rectangle, separation arm lifts cut OLED glass panel, vacuum gripper transfers panel to inspection rack — water rinse and subtle fingerprints on gloves",
    cameraMovement: "slow tracking along glass line",
    cameraAngle: "close-up manufacturing shot",
    lighting: "bright cleanroom-style panel lighting",
    environment: "glass cutting and prep zone",
    soundEffects: ["scoring wheel", "vacuum gripper"],
    musicMood: "careful",
    caption: "",
    emotion: "careful",
    transition: "cut",
  },
  {
    key: "pcb_smt",
    purpose: "PCB through SMT — pick place — reflow",
    priority: 1,
    narration:
      "Bare boards enter the SMT line where pick-and-place heads install microchips onto solder paste before the reflow oven bonds them.",
    visualDescription:
      "Overhead SMT line: green PCB enters machine, pick-and-place nozzles dart down placing tiny chips onto paste dots, board advances into orange-glowing reflow tunnel and exits soldered; engineer adjusts feeder reel — one board one machine cycle visible",
    cameraMovement: "overhead static then slow tracking",
    cameraAngle: "overhead production line",
    lighting: "technical green PCB contrast lighting",
    environment: "electronics SMT assembly hall",
    soundEffects: ["pick-and-place rhythm", "reflow oven hum"],
    musicMood: "technological",
    caption: "",
    emotion: "rapid",
    transition: "cut",
  },
  {
    key: "display_prep",
    purpose: "Display bonded and optically tested",
    priority: 2,
    narration:
      "A robotic gripper lifts a display panel, holds it under optical scanners, and the screen illuminates for a pixel test.",
    visualDescription:
      "Display prep: vacuum gripper lifts glass OLED panel from stack, rotates under optical camera, panel backlight ignites color test pattern, gripper places passed panel onto outgoing conveyor — monitor UI blurred unreadable",
    cameraMovement: "slow push-in on panel surface",
    cameraAngle: "close-up product handling",
    lighting: "display glow in dim inspection booth",
    environment: "display preparation clean zone",
    soundEffects: ["vacuum gripper", "panel glow click"],
    musicMood: "sleek",
    caption: "",
    emotion: "careful",
    transition: "cut",
  },
  {
    key: "camera_module",
    purpose: "Camera module micro-assembly",
    priority: 2,
    narration:
      "Micro robotic arms place lens elements into camera housings and a calibration rig aligns the triple-camera module.",
    visualDescription:
      "Macro assembly bench: micro gripper places lens into barrel, sensor board seated, triple module rotates on laser calibration rig, finished module placed in tray by robotic arm — precise mechanical steps visible",
    cameraMovement: "extreme macro static with micro drift",
    cameraAngle: "extreme macro close-up",
    lighting: "dramatic macro with lens reflections",
    environment: "optical module assembly lab",
    soundEffects: ["precision clicks", "calibration tone"],
    musicMood: "intricate",
    caption: "",
    emotion: "intricate",
    transition: "cut",
  },
  {
    key: "battery_prep",
    purpose: "Battery cells inspected before install",
    priority: 2,
    narration:
      "Battery cells roll through a safety inspection conveyor before a technician loads one into a waiting phone chassis.",
    visualDescription:
      "Battery prep: lithium cells on inspection conveyor pass voltage probe, technician picks passed cell with alignment tool, guides into midnight blue phone mid-frame on fixture, presses until seated — adjacent robot prepares next cell",
    cameraMovement: "side angle static documentary shot",
    cameraAngle: "medium assembly shot",
    lighting: "neutral factory overhead LEDs",
    environment: "battery preparation station",
    soundEffects: ["probe beep", "alignment click"],
    musicMood: "cautious",
    caption: "",
    emotion: "careful",
    transition: "cut",
  },
  {
    key: "motherboard_install",
    purpose: "Motherboard lowered into frame",
    priority: 1,
    narration:
      "On the main line, a robotic arm lowers the motherboard into the empty frame while drivers torque mounting screws.",
    visualDescription:
      "Assembly pallet: empty phone frame clamped on moving pallet, robotic arm descends with green motherboard, aligns connector ports, presses into frame, automated screw driver travels rail torquing fasteners, pallet advances — synchronized single-line motion",
    cameraMovement: "slow tracking along pallet",
    cameraAngle: "side-angle assembly shot",
    lighting: "bright assembly station lighting",
    environment: "main phone assembly conveyor",
    soundEffects: ["robot descend", "screw torque", "pallet roll"],
    musicMood: "momentum",
    caption: "",
    emotion: "building",
    transition: "cut",
  },
  {
    key: "camera_install",
    purpose: "Triple cameras mounted on back",
    priority: 2,
    narration:
      "Triple camera modules are seated into the back housing and torqued to spec as the frame advances.",
    visualDescription:
      "Back housing station: worker places triple camera module into rear cutout, alignment pins engage, torque driver fastens screws in sequence, module sits flush — phone back shown with vertical camera array consistent design",
    cameraMovement: "close-up static on back housing",
    cameraAngle: "close-up assembly shot",
    lighting: "focused assembly bench lighting",
    environment: "rear module installation station",
    soundEffects: ["torque clicks", "module seat"],
    musicMood: "precise",
    caption: "",
    emotion: "focused",
    transition: "cut",
  },
  {
    key: "speaker_connectors",
    purpose: "Speakers and connectors installed",
    priority: 3,
    narration:
      "Small speaker drivers and USB connector boards are pressed into the chassis before the display is added.",
    visualDescription:
      "Internal assembly: technician presses speaker module into bracket, connects ribbon cable with tweezers, seats USB-C connector board into frame slot, presses retention clip — hands only, looking at components not camera",
    cameraMovement: "macro static on internal chassis",
    cameraAngle: "macro internal assembly",
    lighting: "bright bench magnifier lamp",
    environment: "internal component installation bench",
    soundEffects: ["clip snap", "cable seat"],
    musicMood: "detailed",
    caption: "",
    emotion: "meticulous",
    transition: "cut",
  },
  {
    key: "display_install",
    purpose: "Display seated and pressed",
    priority: 1,
    narration:
      "The edge-to-edge display is aligned and pressed into the frame as adhesive bonds the glass to the housing.",
    visualDescription:
      "Display install: robotic arm lowers OLED panel onto frame, alignment pins guide glass, press head descends bonding display, slight machine vibration, completed front shown with edge-to-edge glass — then frame moves on conveyor",
    cameraMovement: "slow push-in on press cycle",
    cameraAngle: "medium front assembly shot",
    lighting: "reflections on bonded glass",
    environment: "display bonding press station",
    soundEffects: ["press descend", "seal hum"],
    musicMood: "satisfying",
    caption: "",
    emotion: "satisfying",
    transition: "cut",
  },
  {
    key: "back_panel_install",
    purpose: "Back panel aligned and sealed",
    priority: 1,
    narration:
      "The back panel drops onto alignment pins and a press seals the completed NovaTech X9 chassis.",
    visualDescription:
      "Back panel station: robotic arm lowers midnight blue back panel onto pins, adhesive press closes, phone rotates on fixture showing complete device, worker removes to outgoing belt — same phone design as prior shots",
    cameraMovement: "controlled orbit half-step on fixture",
    cameraAngle: "medium product assembly",
    lighting: "premium realistic product reflections",
    environment: "final seal station",
    soundEffects: ["panel drop", "press close"],
    musicMood: "crescendo",
    caption: "",
    emotion: "complete",
    transition: "cut",
  },
  {
    key: "automated_testing",
    purpose: "Automated functional test tunnel",
    priority: 1,
    narration:
      "Completed phones roll through a test tunnel where probes exercise buttons and sensors automatically.",
    visualDescription:
      "Test tunnel: phone on conveyor enters automated station, mechanical probes press side buttons, sensors flash pass indicators, phone exits to next lane — engineer watches panel with blurred unreadable graphs",
    cameraMovement: "tracking through test tunnel",
    cameraAngle: "medium wide QC line",
    lighting: "clinical bright test lighting",
    environment: "automated functional test hall",
    soundEffects: ["probe taps", "conveyor rollers"],
    musicMood: "assured",
    caption: "",
    emotion: "confident",
    transition: "cut",
  },
  {
    key: "display_touch_test",
    purpose: "Touchscreen pattern test",
    priority: 2,
    narration:
      "A robotic finger traces diagnostic patterns across the live touchscreen while the display shows test graphics.",
    visualDescription:
      "Touch test station: phone clamped in fixture, robotic probe finger traces grid pattern on illuminated screen, colors shift under test sequence, probe lifts and phone released to belt — single phone single action",
    cameraMovement: "static close-up on screen",
    cameraAngle: "close-up QC shot",
    lighting: "screen glow with overhead clinical light",
    environment: "display and touch QC booth",
    soundEffects: ["probe tap", "test tone"],
    musicMood: "technical",
    caption: "",
    emotion: "assured",
    transition: "cut",
  },
  {
    key: "charging_test",
    purpose: "Charging port verification",
    priority: 3,
    narration:
      "Each device is connected to a charging test rig that verifies the port and battery charge cycle.",
    visualDescription:
      "Charging rig: automated arm inserts USB-C test plug into phone port, indicator LED turns green on rig, phone disconnects and rolls forward — simple single motion focus",
    cameraMovement: "static side close-up",
    cameraAngle: "close-up port test",
    lighting: "focused bench lighting",
    environment: "charging verification station",
    soundEffects: ["plug insert", "relay click"],
    musicMood: "technical",
    caption: "",
    emotion: "assured",
    transition: "cut",
  },
  {
    key: "cleaning_film",
    purpose: "Polish and protective film",
    priority: 3,
    narration:
      "Soft brushes polish the glass while a roller applies protective film before final visual inspection.",
    visualDescription:
      "Finishing line: phone in rotating clamp, brushes polish glass removing smudges, film roller applies protective layer, gripper lifts phone under bright cone light, inspector rotates device checking reflections",
    cameraMovement: "slow push along finishing line",
    cameraAngle: "close-up finishing shot",
    lighting: "sparkling inspection highlights",
    environment: "cleaning and film application station",
    soundEffects: ["brush spin", "film roller"],
    musicMood: "polished",
    caption: "",
    emotion: "pristine",
    transition: "cut",
  },
  {
    key: "packaging",
    purpose: "Boxing on automated line",
    priority: 1,
    narration:
      "Robotic arms box each phone with cable and inserts, close the lid, and stack cartons on the outbound pallet.",
    visualDescription:
      "Packaging line: gripper places phone in plain white box, drops cable and cardboard cradle, lid press closes, carton conveyed to stacker arm on pallet — labels face away from camera",
    cameraMovement: "overhead slow tracking",
    cameraAngle: "overhead packaging line",
    lighting: "clean commercial packaging light",
    environment: "outbound packaging conveyor",
    soundEffects: ["box press", "conveyor", "stacker"],
    musicMood: "efficient",
    caption: "",
    emotion: "complete",
    transition: "cut",
  },
  {
    key: "hero_outbound",
    purpose: "Finished phones on moving line — documentary finale",
    priority: 1,
    narration:
      "Rows of identical finished phones ride the outbound conveyor while assembly stations still run behind them.",
    visualDescription:
      "Low-angle documentary tracking: identical midnight blue NovaTech X9 phones advance on green conveyor toward camera, robotic arms and workers soft-focused in background still operating, stacked plain boxes on pallet, subtle machine vibration and floor reflections — phones moving not static hero table",
    cameraMovement: "slow documentary dolly along conveyor, controlled not flying",
    cameraAngle: "low-angle tracking along line",
    lighting: "realistic factory LEDs with natural bokeh",
    environment: "active outbound line with production behind",
    soundEffects: ["conveyor", "distant servos", "ventilation"],
    musicMood: "subtle triumphant",
    caption: "",
    emotion: "premium",
    transition: "fade",
  },
];
