import type { SceneTemplate } from "../types";

/**
 * Story beats for voiceover-led shorts.
 * People are shot medium-close so faces stay readable — wide shots stay empty of tiny figures.
 */
export function buildNarrativeScenes(idea: string): SceneTemplate[] {
  const hookLine = idea.split(/[.!?]/)[0].trim();
  const villagePolice = /\bgirl\b/i.test(idea) && /\bvillage\b/i.test(idea) && /\bpolice\b/i.test(idea);

  if (villagePolice) {
    return villagePoliceOfficerScenes();
  }

  return [
    {
      key: "opening",
      purpose: "Hook and establishment",
      priority: 1,
      narration: `It began quietly. ${hookLine}.`,
      visualDescription: `Empty establishing place from the story: ${hookLine}, wide environment only, no tiny distant people, atmospheric light`,
      cameraMovement: "slow push-in",
      cameraAngle: "wide establishing shot",
      lighting: "golden natural light with depth",
      environment: "story setting established from the idea",
      soundEffects: ["ambient atmosphere"],
      musicMood: "hopeful",
      caption: "",
      emotion: "curious",
      transition: "cut",
    },
    {
      key: "character",
      purpose: "Protagonist face",
      priority: 1,
      narration: "They carried that wish like a secret they were finally ready to speak.",
      visualDescription: `Medium close-up of the protagonist from ${hookLine}, waist-up, face filling the upper frame, two eyes nose and mouth sharp and visible, looking just off camera, consistent wardrobe`,
      cameraMovement: "slow push-in",
      cameraAngle: "medium close-up",
      lighting: "soft window or sun on the face",
      environment: "primary story location, background softly blurred",
      soundEffects: ["soft ambience"],
      musicMood: "building",
      caption: "",
      emotion: "determined",
      transition: "cut",
    },
    {
      key: "discovery",
      purpose: "Key discovery or event",
      priority: 1,
      narration: "Then the path ahead became real.",
      visualDescription: `Close-up of the protagonist's face reacting to ${hookLine}, eyes and expression readable, hands or a key object in the lower frame`,
      cameraMovement: "slow push-in",
      cameraAngle: "close-up",
      lighting: "dramatic but face still lit",
      environment: "story location intensified",
      soundEffects: ["dramatic accent"],
      musicMood: "suspense",
      caption: "",
      emotion: "hopeful",
      transition: "cut",
    },
    {
      key: "escalation",
      purpose: "Rising action",
      priority: 2,
      narration: "Each day they trained the dream into a habit.",
      visualDescription: `Medium shot of the protagonist doing the work of ${hookLine}, face clearly visible, body in motion, not a distant silhouette`,
      cameraMovement: "slow tracking follow",
      cameraAngle: "medium shot",
      lighting: "natural cinematic light",
      environment: "evolving story environment",
      soundEffects: ["effort ambience"],
      musicMood: "intense",
      caption: "",
      emotion: "focused",
      transition: "cut",
    },
    {
      key: "climax",
      purpose: "Climactic moment",
      priority: 1,
      narration: "The moment they had imagined finally arrived.",
      visualDescription: `Medium close-up hero beat for ${hookLine}, face large and sharp, proud or stunned expression, two eyes nose mouth visible`,
      cameraMovement: "slow push-in",
      cameraAngle: "medium close-up",
      lighting: "bright motivated light on the face",
      environment: "climax location",
      soundEffects: ["climactic swell"],
      musicMood: "epic",
      caption: "",
      emotion: "proud",
      transition: "cut",
    },
    {
      key: "resolution",
      purpose: "Resolution and payoff",
      priority: 1,
      narration: "The village would remember how it started — with one person who refused to stay small.",
      visualDescription: `Intimate close-up of the protagonist after ${hookLine}, a real smile, clear eyes, same face as earlier shots`,
      cameraMovement: "slow pull-out",
      cameraAngle: "close-up",
      lighting: "soft warm resolution lighting",
      environment: "resolved story setting",
      soundEffects: ["soft wind"],
      musicMood: "emotional",
      caption: "",
      emotion: "resolved",
      transition: "fade",
    },
  ];
}

function villagePoliceOfficerScenes(): SceneTemplate[] {
  const girl =
    "Meera, a 17-year-old village girl, South Asian, dark braid, warm brown eyes, simple faded cotton salwar kameez, clear photoreal face with two eyes a nose and a mouth";

  return [
    {
      key: "opening",
      purpose: "Village morning",
      priority: 1,
      narration: "In a small village, a girl named Meera watched the road the way other children watched the sky.",
      visualDescription:
        "Empty Indian village lane at sunrise, mud houses, neem trees, dust in golden light, no people close to camera, no tiny faceless figures",
      cameraMovement: "slow push-in",
      cameraAngle: "wide establishing shot",
      lighting: "warm sunrise",
      environment: "rural Indian village street",
      soundEffects: ["birds", "distant cattle"],
      musicMood: "hopeful",
      caption: "",
      emotion: "curious",
      transition: "cut",
    },
    {
      key: "character",
      purpose: "Meet Meera",
      priority: 1,
      narration: "She wanted to wear the khaki. She wanted to become a police officer.",
      visualDescription: `Medium close-up of ${girl}, waist-up in a village courtyard, face filling the upper frame, looking toward the road with a determined expression, sunlight on her cheek`,
      cameraMovement: "slow push-in",
      cameraAngle: "medium close-up",
      lighting: "soft morning sun on the face",
      environment: "village courtyard, blurred mud walls",
      soundEffects: ["soft village ambience"],
      musicMood: "building",
      caption: "",
      emotion: "determined",
      transition: "cut",
    },
    {
      key: "discovery",
      purpose: "She sees a police officer",
      priority: 1,
      narration: "Every time a police jeep stopped at the tea stall, she stood a little taller.",
      visualDescription: `Close-up of ${girl} watching from the side of a village tea stall, her face sharp and readable, a khaki police uniform slightly out of focus behind her`,
      cameraMovement: "slow push-in",
      cameraAngle: "close-up",
      lighting: "dappled afternoon light on her face",
      environment: "village tea stall",
      soundEffects: ["jeep idle", "tea stall chatter"],
      musicMood: "suspense",
      caption: "",
      emotion: "hopeful",
      transition: "cut",
    },
    {
      key: "escalation",
      purpose: "She studies and trains",
      priority: 2,
      narration: "Books after the fields. Running before sunrise. The dream became a routine.",
      visualDescription: `Medium shot of ${girl} studying by a kerosene lamp then jogging on a village path, face clearly visible in both beats, no distant blob head`,
      cameraMovement: "slow tracking follow",
      cameraAngle: "medium shot",
      lighting: "lamp light then dawn",
      environment: "village home and dirt path",
      soundEffects: ["pages", "footsteps"],
      musicMood: "intense",
      caption: "",
      emotion: "focused",
      transition: "cut",
    },
    {
      key: "climax",
      purpose: "She earns the uniform",
      priority: 1,
      narration: "Years later the same village saw her step out in uniform.",
      visualDescription: `Medium close-up of ${girl} now a young police officer in a khaki uniform and cap, same face as the girl, two eyes nose mouth sharp, proud quiet smile`,
      cameraMovement: "slow push-in",
      cameraAngle: "medium close-up",
      lighting: "bright daylight on her face",
      environment: "village square",
      soundEffects: ["soft crowd murmur"],
      musicMood: "epic",
      caption: "",
      emotion: "proud",
      transition: "cut",
    },
    {
      key: "resolution",
      purpose: "The village remembers",
      priority: 1,
      narration: "The girl who once watched the road now protected it.",
      visualDescription: `Close-up of adult Meera's face in khaki, same warm brown eyes, a small real smile, village houses softly blurred behind her`,
      cameraMovement: "slow pull-out",
      cameraAngle: "close-up",
      lighting: "soft warm late-afternoon light",
      environment: "village road",
      soundEffects: ["soft wind"],
      musicMood: "emotional",
      caption: "",
      emotion: "resolved",
      transition: "fade",
    },
  ];
}
