import type { SceneTemplate } from "../types";

export function buildNarrativeScenes(idea: string): SceneTemplate[] {
  const hookLine = idea.split(/[.!?]/)[0].trim();
  return [
    {
      key: "opening",
      purpose: "Hook and establishment",
      priority: 1,
      narration: `It began quietly. ${hookLine}.`,
      visualDescription: `Opening establishing shot: ${hookLine}, atmospheric wide shot, cinematic environment, strong visual hook in first seconds`,
      cameraMovement: "slow push-in",
      cameraAngle: "wide establishing shot",
      lighting: "moody cinematic lighting with depth",
      environment: "story setting established from the idea",
      soundEffects: ["ambient atmosphere"],
      musicMood: "mysterious",
      caption: "THE BEGINNING",
      emotion: "curious",
      transition: "cut",
    },
    {
      key: "character",
      purpose: "Introduce protagonist",
      priority: 1,
      narration: "Someone was about to discover that nothing was as it seemed.",
      visualDescription: `Protagonist enters the scene related to: ${hookLine}, medium shot, natural movement, consistent character appearance`,
      cameraMovement: "slow tracking follow",
      cameraAngle: "medium shot",
      lighting: "natural cinematic light",
      environment: "primary story location",
      soundEffects: ["footsteps"],
      musicMood: "building",
      caption: "",
      emotion: "anticipation",
      transition: "cut",
    },
    {
      key: "discovery",
      purpose: "Key discovery or event",
      priority: 1,
      narration: "Then, the unexpected moment arrived.",
      visualDescription: `Discovery moment: ${hookLine}, tension building, close-up on key object or reaction, dramatic reveal`,
      cameraMovement: "quick push-in",
      cameraAngle: "close-up",
      lighting: "dramatic contrast lighting",
      environment: "story location intensified",
      soundEffects: ["dramatic accent"],
      musicMood: "suspense",
      caption: "DISCOVERY",
      emotion: "shocked",
      transition: "cut",
    },
    {
      key: "escalation",
      purpose: "Rising action",
      priority: 2,
      narration: "Each step forward revealed a deeper truth.",
      visualDescription: `Escalation scene: ${hookLine}, dynamic movement, obstacles or revelations, medium-wide action shot`,
      cameraMovement: "dynamic tracking",
      cameraAngle: "medium wide shot",
      lighting: "dramatic shifting light",
      environment: "evolving story environment",
      soundEffects: ["tension ambience"],
      musicMood: "intense",
      caption: "",
      emotion: "tense",
      transition: "cut",
    },
    {
      key: "climax",
      purpose: "Climactic moment",
      priority: 1,
      narration: "Everything came together in one decisive moment.",
      visualDescription: `Climactic scene: ${hookLine}, peak emotional intensity, dynamic camera, hero moment`,
      cameraMovement: "dramatic crane or orbit",
      cameraAngle: "low-angle hero shot",
      lighting: "dramatic backlight and rim light",
      environment: "climax location",
      soundEffects: ["climactic swell"],
      musicMood: "epic",
      caption: "CLIMAX",
      emotion: "intense",
      transition: "cut",
    },
    {
      key: "resolution",
      purpose: "Resolution and payoff",
      priority: 1,
      narration: "In the end, the story left everything changed.",
      visualDescription: `Resolution: ${hookLine}, emotional payoff, calm after storm, reflective wide or intimate close shot`,
      cameraMovement: "slow pull-out",
      cameraAngle: "wide reflective shot",
      lighting: "soft warm resolution lighting",
      environment: "resolved story setting",
      soundEffects: ["soft wind or calm ambience"],
      musicMood: "emotional",
      caption: "THE END",
      emotion: "resolved",
      transition: "fade",
    },
  ];
}
